language: node_js
node_js:
  - 6
  - 7
# jdk
# kafka
install:
#  - npm i npminstall && npminstall
#  - wget http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.tar.gz
#  - tar zxvf jdk-8u121-linux-x64.tar.gz
#  - cd jdk1.8.0_121
#  - export JAVA_HOME=`pwd`
#  - export JRE_HOME=${JAVA_HOME}/jre  
#  - export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib  
#  - export PATH=${JAVA_HOME}/bin:$PATH
# install jdk
  - sudo apt-get update
  - sudo apt-get install default-jre
  - sudo apt-get install default-jdk
  - echo $PATH
  - java -version
  - wget http://www-us.apache.org/dist/kafka/0.10.1.1/kafka-0.10.1.1-src.tgz
  - tar zxvf kafka-0.10.1.1-src.tgz
  - cd kafka-0.10.1.1-src
  - bin/kafka-server-start.sh config/server.properties
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
