language: node_js
cache: yarn
node_js:
  - 6
  - 7
# jdk
# kafka
before_script:
  - sudo apt-get update
  - sudo apt-get install default-jre
  - sudo apt-get install default-jdk
  - echo $PATH
  - java -version
  - wget http://apache.claz.org/kafka/0.10.0.0/kafka_2.11-0.10.0.0.tgz
  - tar zxvf kafka_2.11-0.10.0.0.tgz
  - cd kafka_2.11-0.10.0.0
  - bin/zookeeper-server-start.sh config/zookeeper.properties >/dev/null &
  - bin/kafka-server-start.sh config/server.properties >/dev/null &

install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
