language: node_js
node_js:
  - "6"
  - "7"
install:
  - npm i npminstall && npminstall
  - wget http://www-us.apache.org/dist/kafka/0.9.0.1/kafka-0.9.0.1-src.tgz
  - tar zxvf kafka-0.9.0.1-src.tgz
  - cd kafka-0.9.0.1-src
  - bin/kafka-server-start.sh config/server.properties
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
